server:
  port: 8100
  servlet:
    context-path: /aggregate
spring:
  application:
    name: aggregate-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        # nacos服务地址通过启动脚本指定
        username: ${nacos_username}
        password: ${nacos_password}
        server-addr: ${nacos_server}
        access-key: SecretKey012345678901234567890123456789012345678901234567890123456789
      config:
        # nacos服务地址通过启动脚本指定
        username: ${nacos_username}
        password: ${nacos_password}
        server-addr: ${nacos_server}
        access-key: SecretKey012345678901234567890123456789012345678901234567890123456789
logging:
  level:
    root: info
