server:
  port: 8099
  servlet:
    context-path: /user
spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        # nacos服务地址通过启动脚本指定
        username: ${nacos_username}
        password: ${nacos_password}
        server-addr: ${nacos_server}
        access-key: ${nacos_key}
      config:
        # nacos服务地址通过启动脚本指定
        username: ${nacos_username}
        password: ${nacos_password}
        server-addr: ${nacos_server}
        access-key: ${nacos_key}

logging:
  level:
    root: info
