server:
  port: 8099
spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # nacos服务地址通过启动脚本指定
        username: ${nacos_username}
        password: ${nacos_password}
        server-addr: ${nacos_server}
        access-key: SecretKey012345678901234567890123456789012345678901234567890123456789
      config:
        # nacos服务地址通过启动脚本指定
        username: ${nacos_username}
        password: ${nacos_password}
        server-addr: ${nacos_server}
        access-key: SecretKey012345678901234567890123456789012345678901234567890123456789

logging:
  level:
    root: info
