spring:
  cloud:
    nacos:
      discovery:
        namespace: spring-cloud-handbook
        group: dev
      config:
        enabled: true
        namespace: spring-cloud-handbook
        group: dev
        config-retry-time: 3000
        refresh-enabled: true
        context-path: nacos # 注意要和nacos server配置文件里的context-path一致
  config:
    import:
      # 注意在nacos建配置的时候data-id要是common-redis.yaml，估计是想省略一个配置文件的扩展名字段
      - optional:nacos:user-service.yaml
      - optional:nacos:common-redis.yaml?group=dev&refreshEnabled=true
      - optional:nacos:common-database.yaml?group=dev&refreshEnabled=true
      - optional:nacos:common-mail.yaml?group=dev&refreshEnabled=true
